name: Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Amazon ECR
    runs-on: ubuntu-latest
    steps:
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: ghcr.io/vtcs5704-team1/vib/ui:5f2240b7ca7e4240c6ffd98064e1e90bff034d71 #TODO: CHANGE TAG TO 'LATEST'